sudo: false
language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install tox-travis coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - coveralls
notifications:
  email: false